name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - latest
          - 0.20.1
          - 0.19.0
          - 0.18.0
          - 0.16.1  # oldest supported version
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: lychee --version
          version: ${{ matrix.version }}
          gitref: ${{ github.head_ref || github.ref_name }}
