name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        include:
          # Test on Ubuntu with all versions
          - os: ubuntu-latest
            version: latest
          - os: ubuntu-latest
            version: 0.20.1
          - os: ubuntu-latest
            version: 0.19.0
          - os: ubuntu-latest
            version: 0.18.0
          - os: ubuntu-latest
            version: 0.16.1
          # Test on macOS with versions that have .tar.gz files (0.19.0+)
          - os: macos-latest
            version: latest
          - os: macos-latest
            version: 0.20.1
          - os: macos-latest
            version: 0.19.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: lychee --version
          version: ${{ matrix.version }}
          gitref: ${{ github.head_ref || github.ref_name }}
