name: Test

on:
  push:
    branches: ["main", "implement-plugin"]
  pull_request:
    branches: ["main"]

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: lychee --version